from .agents import MusicCoordinatorAgent
from .accuracy_v2_finalization_v2 import install_accuracy_v2_finalization
from .accuracy_v2_release_recovery import install_accuracy_v2_release_recovery
from .quality_extension import install_quality_extension

install_quality_extension()
install_accuracy_v2_release_recovery()
install_accuracy_v2_finalization()

__all__ = ["MusicCoordinatorAgent"]
